name: Deploy Storybook
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          npm ci
          
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

  #    - name: Install and Build
   #     run: |
    #      npm ci
     #     npm run build
      #    npm run build-storybook

     # - name: Upload GitHub Pages artifact
      #  uses: actions/upload-pages-artifact@v2.0.0
       # with:
        #  path: storybook-static
      - name: Deploy Storybook to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-storybook-to-github-pages@c7d2a479f2ec3d87d1131357f328e0e40c60da20
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: storybook-static
          build_command: |
            npm run build -- docs
            npm run build-storybook
    #  - name: Deploy
     #   uses: JamesIves/github-pages-deploy-action@3.6.2
      #  with:
       #   branch: gh-pages
        #  folder: storybook-static # output folder from `npm run build-storybook`
